# Generated by Django 3.2.8 on 2021-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango_app', '0002_auto_20211125_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='dt_end_role',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
