# Generated by Django 3.2.8 on 2021-11-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tango_app', '0003_alter_user_role_dt_end_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
