# Generated by Django 3.2.8 on 2021-12-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tango_app', '0004_task_user_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_role',
        ),
    ]
